import { Profile, ProfileType } from "@/types";

export const quizQuestions = [
  {
    id: 1,
    question: "Which statement sounds most like you?",
    options: [
      { text: "I think too much before making decisions.", profile: "overthinker" },
      { text: "I often question whether I am good enough.", profile: "doubter" },
      { text: "I struggle expressing my thoughts confidently.", profile: "silent-voice" },
      { text: "I know what to do but don't follow through consistently.", profile: "action-seeker" },
      { text: "I know I'm capable of more but feel stuck.", profile: "hidden-leader" },
    ],
  },
  {
    id: 2,
    question: "What frustrates you most right now?",
    options: [
      { text: "Overthinking", profile: "overthinker" },
      { text: "Self-doubt", profile: "doubter" },
      { text: "Fear of judgment", profile: "silent-voice" },
      { text: "Lack of consistency", profile: "action-seeker" },
      { text: "Lack of direction", profile: "hidden-leader" },
    ],
  },
  {
    id: 3,
    question: "What would you most like to improve?",
    options: [
      { text: "Clarity", profile: "overthinker" },
      { text: "Confidence", profile: "doubter" },
      { text: "Communication", profile: "silent-voice" },
      { text: "Discipline", profile: "action-seeker" },
      { text: "Leadership", profile: "hidden-leader" },
    ],
  },
  {
    id: 4,
    question: "When opportunities appear, what usually happens?",
    options: [
      { text: "I overanalyze them.", profile: "overthinker" },
      { text: "I doubt myself.", profile: "doubter" },
      { text: "I stay quiet.", profile: "silent-voice" },
      { text: "I delay taking action.", profile: "action-seeker" },
      { text: "I don't know which direction to choose.", profile: "hidden-leader" },
    ],
  },
  {
    id: 5,
    question: "What is your biggest challenge?",
    options: [
      { text: "Making decisions", profile: "overthinker" },
      { text: "Believing in myself", profile: "doubter" },
      { text: "Speaking up", profile: "silent-voice" },
      { text: "Following through", profile: "action-seeker" },
      { text: "Creating a vision for my future", profile: "hidden-leader" },
    ],
  },
  {
    id: 6,
    question: "Which statement describes you best?",
    options: [
      { text: "I spend too much time in my head.", profile: "overthinker" },
      { text: "I compare myself to others.", profile: "doubter" },
      { text: "I hold back my opinions.", profile: "silent-voice" },
      { text: "I start more than I finish.", profile: "action-seeker" },
      { text: "I know there is more potential inside me.", profile: "hidden-leader" },
    ],
  },
  {
    id: 7,
    question: "What do you fear most?",
    options: [
      { text: "Making the wrong decision.", profile: "overthinker" },
      { text: "Failing.", profile: "doubter" },
      { text: "Being judged.", profile: "silent-voice" },
      { text: "Not reaching my goals.", profile: "action-seeker" },
      { text: "Wasting my potential.", profile: "hidden-leader" },
    ],
  },
  {
    id: 8,
    question: "What do people often tell you?",
    options: [
      { text: "Stop overthinking.", profile: "overthinker" },
      { text: "Believe in yourself.", profile: "doubter" },
      { text: "Speak up more.", profile: "silent-voice" },
      { text: "Just do it.", profile: "action-seeker" },
      { text: "You have so much potential.", profile: "hidden-leader" },
    ],
  },
  {
    id: 9,
    question: "What would change your life most over the next 90 days?",
    options: [
      { text: "Greater clarity.", profile: "overthinker" },
      { text: "More confidence.", profile: "doubter" },
      { text: "Better communication skills.", profile: "silent-voice" },
      { text: "Consistent action.", profile: "action-seeker" },
      { text: "Stronger self-leadership.", profile: "hidden-leader" },
    ],
  },
  {
    id: 10,
    question: "What are you looking for right now?",
    options: [
      { text: "Clear thinking.", profile: "overthinker" },
      { text: "Self-belief.", profile: "doubter" },
      { text: "Better communication.", profile: "silent-voice" },
      { text: "Momentum.", profile: "action-seeker" },
      { text: "Personal growth and leadership.", profile: "hidden-leader" },
    ],
  },
];

export const profiles: Record<ProfileType, Profile> = {
  overthinker: {
    id: "overthinker",
    title: "The Overthinker",
    emoji: "🧠",
    tagline: "Thoughtful. Intelligent. Reflective.",
    gift: "You see possibilities and details others often miss. Your analytical mind is a superpower — when directed well.",
    holding: "You spend so much time searching for certainty that action gets delayed. Thinking becomes a substitute for doing.",
    focus: ["Less analysis", "More trust", "Decisive action"],
    insight: "Clarity rarely comes before action. More often, action creates clarity.",
    challenge: "Make one decision within 60 seconds every day for 7 days. Trust yourself. Observe what happens.",
    cta: "Start Your Awareness Journey",
    ctaLink: "#programs",
    color: "#1a1a2e",
    accentColor: "#D4AF37",
  },
  doubter: {
    id: "doubter",
    title: "The Doubter",
    emoji: "💎",
    tagline: "Caring. Meticulous. Full of untapped potential.",
    gift: "You care deeply and want to do things well. You have more potential than you currently recognize.",
    holding: "You wait until you feel ready. You underestimate your strengths and compare yourself to others.",
    focus: ["Build self-trust", "Recognize your progress", "Act before confidence arrives"],
    insight: "Confidence is not found. Confidence is built through action.",
    challenge: "Each evening write down three things you did well today. No matter how small. Do this for 7 days.",
    cta: "Build Your Confidence",
    ctaLink: "#programs",
    color: "#0d1b2a",
    accentColor: "#D4AF37",
  },
  "silent-voice": {
    id: "silent-voice",
    title: "The Silent Voice",
    emoji: "🎤",
    tagline: "Wise. Observant. With worlds left to express.",
    gift: "You have valuable ideas, wisdom and perspectives. People genuinely benefit when you share them.",
    holding: "Fear of judgment. Fear of saying the wrong thing. Fear of being truly seen.",
    focus: ["Communication", "Expression", "Visibility"],
    insight: "Your voice becomes stronger every time you use it. Silence doesn't protect you — it limits you.",
    challenge: "Speak up once every day. Share an opinion. Ask a question. Express a thought. Do this for 7 days.",
    cta: "Find Your Voice",
    ctaLink: "#programs",
    color: "#0a1628",
    accentColor: "#D4AF37",
  },
  "action-seeker": {
    id: "action-seeker",
    title: "The Action Seeker",
    emoji: "🚀",
    tagline: "Ambitious. Growth-hungry. Ready to execute.",
    gift: "You are ambitious and growth-oriented. You genuinely want to improve your life and have what it takes.",
    holding: "You know more than enough. The challenge is implementation — turning knowledge into consistent action.",
    focus: ["Consistency", "Systems", "Daily non-negotiables"],
    insight: "Success is rarely created by intensity. It is created by consistency.",
    challenge: "Choose one important habit. Do it every day for 7 days. No exceptions. No excuses.",
    cta: "Build Your System",
    ctaLink: "#programs",
    color: "#0f1923",
    accentColor: "#D4AF37",
  },
  "hidden-leader": {
    id: "hidden-leader",
    title: "The Hidden Leader",
    emoji: "👑",
    tagline: "Visionary. Powerful. Waiting to step forward.",
    gift: "You naturally think bigger than your current situation. You have leadership potential that others can feel.",
    holding: "You haven't fully stepped into your own power yet. You are still waiting for permission that will never come.",
    focus: ["Leadership", "Ownership", "Vision", "Responsibility"],
    insight: "Leadership begins the moment you stop waiting and start deciding.",
    challenge: "Ask yourself every morning: 'What would the strongest version of me do today?' Then act accordingly.",
    cta: "Step Into Leadership",
    ctaLink: "#programs",
    color: "#110a1e",
    accentColor: "#D4AF37",
  },
};

export const programs = [
  {
    id: "awareness-journal",
    name: "The Awareness Journal",
    tagline: "The Most Important Meeting Is With Yourself",
    price: 999,
    originalPrice: 1999,
    razorpayAmount: 99900,
    features: [
      "Future Letter To Myself",
      "21-Day Sankalp Journey",
      "Gratitude Practice",
      "Awareness Exercises",
      "Reflection Prompts",
      "Weekly Check-ins",
      "Vision & Conscious Creation",
      "Alignment & Action Pages",
    ],
    highlight: false,
  },
  {
    id: "mindset-mastery",
    name: "Mindset Mastery",
    tagline: "Think Differently. Live Differently.",
    price: 4999,
    originalPrice: 9999,
    razorpayAmount: 499900,
    features: [
      "Stop overthinking framework",
      "Build unshakeable confidence",
      "Overcome self-doubt permanently",
      "Make better decisions faster",
      "Develop empowering beliefs",
      "6 live coaching sessions",
      "Private community access",
      "Lifetime resource access",
    ],
    highlight: false,
  },
  {
    id: "transformation-system",
    name: "Captanova Transformation System™",
    tagline: "From Overthinking to Self-Leadership",
    price: 14999,
    originalPrice: 29999,
    razorpayAmount: 1499900,
    features: [
      "Full Mindset Mastery program",
      "Communication Mastery module",
      "Action Mastery framework",
      "Leadership Mentorship (3 months)",
      "1-on-1 strategy sessions",
      "Daily accountability system",
      "Access to all future programs",
      "Direct WhatsApp support with Renu",
    ],
    highlight: true,
  },
  {
    id: "leadership-mentorship",
    name: "Leadership Mentorship",
    tagline: "Lead Yourself & Others",
    price: 24999,
    originalPrice: 49999,
    razorpayAmount: 2499900,
    features: [
      "Everything in Transformation System",
      "Personal 1-on-1 mentorship (6 months)",
      "Identity transformation deep-dive",
      "Purpose & vision clarity sessions",
      "High-performance habit design",
      "Communication excellence training",
      "Conscious leadership development",
      "VIP priority access & support",
    ],
    highlight: false,
  },
];
